# config.yaml
server:
  host: "localhost"
  port: "3000"
paths:
  restaurants: "./internal/data/restaurants.json"
  menu: "./internal/data/menus.json"
  menu_csv: "./internal/data/restaurant-menus.csv"
  restaurant_csv: "./internal/data/restaurants.csv"
database:
  name: "postgres"
  user: "postgres"
  password: "postgres"
  host: "localhost"
  port: "5432"
  db-address: "jdbc:postgresql://localhost:5432/postgres"


