# config.yaml
server:
  host: "localhost"
  port: "3000"
paths:
  restaurants: "./internal/data/restaurants.json"
  menu: "./internal/data/menus.json"
  menu_csv: "./internal/data/restaurant-menus.csv"
  restaurant_csv: "./internal/data/restaurants.csv"
database:
  name: "postgres"
  user: "postgres"
  password: "postgres"
  host: "localhost"
  port: "5432"
aws:
  access_key_id: "AKIAIOSFODNN7EXAMPLE"
  secret_access_key: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
  region: "eu-central-1"
  endpoint: "http://localhost:4566/"
  token: "token"
secret:
  key: "secret"

