// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	entity "github.com/valentyna-koshelnyk/panda-eats-prototype-api/internal/domain/entity"
)

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

// CalculateTotalOrderPrice provides a mock function with given fields: carts
func (_m *OrderService) CalculateTotalOrderPrice(carts []entity.Cart) float64 {
	ret := _m.Called(carts)

	if len(ret) == 0 {
		panic("no return value specified for CalculateTotalOrderPrice")
	}

	var r0 float64
	if rf, ok := ret.Get(0).(func([]entity.Cart) float64); ok {
		r0 = rf(carts)
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}

// CreateOrder provides a mock function with given fields: userID
func (_m *OrderService) CreateOrder(userID string) error {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetOrderHistory provides a mock function with given fields: userID
func (_m *OrderService) GetOrderHistory(userID string) ([]entity.Order, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderHistory")
	}

	var r0 []entity.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]entity.Order, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) []entity.Order); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateOrderStatusDelivered provides a mock function with given fields: userID, orderID
func (_m *OrderService) UpdateOrderStatusDelivered(userID string, orderID string) error {
	ret := _m.Called(userID, orderID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderStatusDelivered")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(userID, orderID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateOrderStatusShipped provides a mock function with given fields: userID, orderID
func (_m *OrderService) UpdateOrderStatusShipped(userID string, orderID string) error {
	ret := _m.Called(userID, orderID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderStatusShipped")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(userID, orderID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
