// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	"github.com/stretchr/testify/mock"

	"github.com/valentyna-koshelnyk/panda-eats-prototype-api/internal/domain/entity"
	"github.com/valentyna-koshelnyk/panda-eats-prototype-api/internal/utils"
)

// RestaurantService is an autogenerated mock type for the RestaurantService type
type RestaurantService struct {
	mock.Mock
}

// CreateRestaurant provides a mock function with given fields: restaurant
func (_m *RestaurantService) CreateRestaurant(restaurant entity.Restaurant) error {
	ret := _m.Called(restaurant)

	if len(ret) == 0 {
		panic("no return value specified for CreateRestaurant")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.Restaurant) error); ok {
		r0 = rf(restaurant)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteRestaurant provides a mock function with given fields: id
func (_m *RestaurantService) DeleteRestaurant(id int64) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRestaurant")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FilterRestaurants provides a mock function with given fields: category, zip, priceRange
func (_m *RestaurantService) FilterRestaurants(category string, zip string, priceRange string) (*utils.PaginatedResponse, error) {
	ret := _m.Called(category, zip, priceRange)

	if len(ret) == 0 {
		panic("no return value specified for FilterRestaurants")
	}

	var r0 *utils.PaginatedResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (*utils.PaginatedResponse, error)); ok {
		return rf(category, zip, priceRange)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) *utils.PaginatedResponse); ok {
		r0 = rf(category, zip, priceRange)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utils.PaginatedResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(category, zip, priceRange)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateRestaurant provides a mock function with given fields: restaurant
func (_m *RestaurantService) UpdateRestaurant(restaurant entity.Restaurant) error {
	ret := _m.Called(restaurant)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRestaurant")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.Restaurant) error); ok {
		r0 = rf(restaurant)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRestaurantService creates a new instance of RestaurantService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRestaurantService(t interface {
	mock.TestingT
	Cleanup(func())
}) *RestaurantService {
	mock := &RestaurantService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
